version: '3'
services: 
  mailcather:
    image: 'schickling/mailcatcher'
    ports:
    - '7001:1080'
    - '7002:1025'
  
  redis:
   image: 'redis'
   ports:
    - '7003:6379'
   volumes:
    - redisvolume:/data

volumes:
  redisvolume: